#!/usr/bin/env bash
# The C1c mutant round — the planner's number helper by capability, ONE purchase enumeration, the BUTTON rule.
#
# ⛔ FOR EVERY MUTANT, THE TWO QUESTIONS (V4's Part 5, kept):
#   1. CAN IT MOVE ITS ROW'S OWN REFERENCE? m1's references are the COMMITTED games-data files (`--check` regenerates
#      and compares; a mutant of the reader cannot edit them) and the unit test's stub; m2's is the game's own
#      declaration (`canAfford: false`) read at boot, and the unit test; m3's is the BEFORE commit's RECORDING
#      (tools/harness/recorded/c1c-before.json — S1T, ⚖ R12/R13: it was a control worktree at 4d8ee5a69), which the
#      mutant does not touch, plus the pinned opening (6862 / cf8df88462606277); m4's is the unit test's
#      stub, whose button is written in the test.
#   2. DOES A SECOND GUARD MAKE IT REDUNDANT? Named beside the ones where it does.
#
# ⛔ RESTORED FROM A COPY, NEVER FROM GIT — a harness that restores with `git checkout` restores over uncommitted
# work. The script refuses to start on a dirty tree. ⛔ DO NOT EDIT THIS FILE WHILE IT IS RUNNING (bash reads it by
# byte offset).
#
#   bash tools/harness/mutants-c1c.sh <out-dir> [name-filter]
set -uo pipefail
cd "$(dirname "$0")/../.."
OUT="${1:?usage: mutants-c1c.sh <out-dir> [name-filter]}"
ONLY="${2:-}"
mkdir -p "$OUT"
if [ -n "$(git status --porcelain)" ]; then echo "REFUSING: the tree is dirty. Commit first — a mutant round restores over whatever is here."; exit 1; fi
AUTO=loader/tmt-auto.js
PLAN=loader/tmt-planner.js
cp "$AUTO" "$OUT/tmt-auto.js.orig"
cp "$PLAN" "$OUT/tmt-planner.js.orig"
restore() { cp "$OUT/tmt-auto.js.orig" "$AUTO"; cp "$OUT/tmt-planner.js.orig" "$PLAN"; }
trap restore EXIT

mutant() {
  local name="$1" mut="$2"; shift 2
  if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then return 0; fi
  restore
  python3 -c "$mut" || { echo "$name: THE MUTATION DID NOT APPLY"; return 1; }
  echo "=== $name ==="
  git --no-pager diff --stat -- "$AUTO" "$PLAN"
  bash -c "$*" > "$OUT/$name.log" 2>&1
  echo "$name: exit $? — $(grep -cE '^(RED|STALE|not ok)' "$OUT/$name.log") RED row(s), $(grep -cE '^(GREEN|ok )' "$OUT/$name.log") green"
  grep -E '^(RED|STALE|not ok)' "$OUT/$name.log" | cut -c1-260
  restore
  git --no-pager diff --stat -- "$AUTO" "$PLAN" | grep . && echo "!! NOT RESTORED" || echo "restored: diff is empty"
}

G="node tools/harness/gates-c1c.mjs --no-summary --no-write --part"
UNIT="node --test loader/c1c.test.mjs 2>&1 | grep -E '^(not )?ok '"

# ⛔ THE BRIEF'S OWN MUTANT: the helper names a library again — `x instanceof Decimal ? x : new Decimal(x)`. It must red
# on the ExpantaNum game: the reader throws there again, so the regenerated file differs from the committed one.
mutant m1-the-helper-names-a-library-again \
  "p='$PLAN';s=open(p).read();o='    var C = numType();\n    if (!C) throw new Error(';assert o in s;s=s.replace(o,'    return x instanceof Decimal ? x : new Decimal(x === undefined || x === null ? 0 : x);\n    var C = numType();\n    if (!C) throw new Error(');o2='  function isDec(x) { var C = numType(); return !!C && x instanceof C; }';assert o2 in s;s=s.replace(o2,'  function isDec(x) { return x instanceof Decimal; }');open(p,'w').write(s)" \
  "node tools/currency-data.mjs --check --ids the-hyperoperator-tree,the-pro-tree --jobs 2; $UNIT"

# ⛔ THE BRIEF'S OWN MUTANT: the enumeration admits a face (no display-only guard). Part 4's UR row must red (the six
# faces become purchase ids at boot). A second guard: the unit test on `isPurchaseDef` reds too.
mutant m2-the-enumeration-admits-a-face \
  "p='$AUTO';s=open(p).read();o='  function displayOnly(v) { return v.canAfford === false; }';assert o in s;s=s.replace(o,'  function displayOnly(v) { return false; }');open(p,'w').write(s)" \
  "$G 4"

# ⛔ THE BRIEF'S OWN MUTANT: numeric order changed (descending). Part 3 (inertness against the BEFORE commit, and the
# pinned opening) must red. A second guard: the unit test's `[3, 21, 100, …]`.
mutant m3-numeric-order-changed \
  "p='$AUTO';s=open(p).read();o='    var o = numIds(obj);\n    for (var id in obj) if (isNaN(id)';assert o in s;s=s.replace(o,'    var o = numIds(obj).reverse();\n    for (var id in obj) if (isNaN(id)');open(p,'w').write(s)" \
  "$G 3 --pool 4 --repeat 1; $UNIT"

# the kind judges a purchase by the buyable's OWN amount again (no `raises`): a button spends once a tick and reports
# nothing bought. The unit test's counted-to-exhaustion button must red.
mutant m4-a-button-judged-by-its-own-amount \
  "p='$AUTO';s=open(p).read();o='        var slot = amountSlot(l, id);';assert o in s;s=s.replace(o,'        var slot = id;');open(p,'w').write(s)" \
  "$UNIT"
