// docs/games.md — the roster, generated from manifests/ so it cannot drift from what the loader actually hosts.
//
// The table lived in README.md and was kept by hand. It is 40 rows today and the roster is meant to grow to the
// census top 100, at which point a hand-kept copy is both most of the README and certain to go stale — the
// manifests are the source of truth for every column in it.
//
//   node tools/games-table.mjs           rewrite docs/games.md
//   node tools/games-table.mjs --check   report without writing; exit 1 when it is out of date or inconsistent
//
// `checkGamesTable()` is the same check as a value, for gate G6 in gates.mjs.
import fs from 'node:fs';
import path from 'node:path';
import { REPO, GAMES, readManifest } from './harness/lib.mjs';
import { sourcesOf } from './census-figures.mjs';

export const OUT = 'docs/games.md';
export const DECLINED = 'manifests/declined.json';
const LIVE = 'https://peerinfinity.github.io/tmt-loader/';
const esc = (s) => String(s).replace(/\|/g, '\\|');

/** The roster as the manifests declare it, in `manifests/index.json` order. */
export function rosterFromManifests() {
  const index = JSON.parse(fs.readFileSync(path.join(REPO, 'manifests/index.json'), 'utf8'));
  return index.map(({ id }) => {
    const m = JSON.parse(fs.readFileSync(path.join(REPO, `manifests/${id}.json`), 'utf8'));
    const up = m.upstream || {};
    return { id, name: m.name, repo: up.repo || '', commit: (up.commit || '').slice(0, 7),
      engine: (m.engine && m.engine.tmtNum) || '?', license: (m.license && m.license.verdict) || '?' };
  });
}

export function render(rows) {
  return [
    '# The games',
    '',
    `${rows.length} games, in the order they were added — the same order as \`manifests/index.json\`. To choose a game`,
    'to play, use the [TMT fork census](https://peerinfinity.github.io/tmt-fork-census/), which ranks and describes',
    'them. The first two were added by hand; the rest by `tools/add-game.mjs` from the',
    '[tmt-fork-census](https://github.com/PeerInfinity/tmt-fork-census) top 100, choosing games whose own play page',
    'no longer works.',
    '',
    'Each game lives under `games/<id>/` as a **git subtree**, pristine at the upstream commit its manifest records,',
    'and keeps its own license files and credits inside that subtree. `play` opens it on the published loader;',
    '`mobile` opens the same game in the [mobile layout](mobile.md).',
    '',
    '> Generated by `node tools/games-table.mjs` from `manifests/` — do not edit by hand.',
    '',
    '| id | game | play | upstream | engine | license |',
    '|---|---|---|---|---|---|',
    ...rows.map((r) => `| \`${r.id}\` | ${esc(r.name)} | [play](${LIVE}?mod=${encodeURIComponent(r.id)}) · [mobile](${LIVE}?mod=${encodeURIComponent(r.id)}&mobile=1) | \`${esc(r.repo)}\` @ \`${r.commit}\` | TMT ${esc(r.engine)} | ${esc(r.license)} |`),
    '',
  ].join('\n');
}

/** The ids the COMMITTED file lists, read back out of its table — not out of the generator. */
export function idsInDoc(text) {
  return [...text.matchAll(/^\| `([^`]+)` \| /gm)].map((m) => m[1]);
}

/**
 * Gate G6. Comparing the file to what the generator would emit proves only that the two AGREE — a generator that
 * dropped a game, run to regenerate the file, leaves them agreeing on the wrong roster. Measured: a one-character
 * mutant (`index.slice(0, -1)`) plus a regenerate was GREEN until this check read its roster separately.
 *
 * So the ids are compared against `manifests/index.json` read HERE, directly — not through `rosterFromManifests()`,
 * which is the generator's own path and would carry the same bug into both sides of the comparison. That file is
 * what the loader's picker enumerates, so it is the roster of record for the one claim this document makes: that
 * it lists every game the loader hosts, once, in that order.
 */
export function checkGamesTable() {
  const f = path.join(REPO, OUT);
  const rows = rosterFromManifests();
  const want = render(rows);
  const have = fs.existsSync(f) ? fs.readFileSync(f, 'utf8') : null;
  const problems = [];
  if (have === null) problems.push(`${OUT} does not exist`);
  else if (have !== want) problems.push(`${OUT} is out of date — run: node tools/games-table.mjs`);

  // read independently of rosterFromManifests(): see the note above
  const manifestIds = JSON.parse(fs.readFileSync(path.join(REPO, 'manifests/index.json'), 'utf8')).map((e) => e.id);
  if (rows.length !== manifestIds.length) problems.push(`the generator built ${rows.length} rows from ${manifestIds.length} manifests`);
  const docIds = have === null ? [] : idsInDoc(have);
  const missing = manifestIds.filter((i) => !docIds.includes(i));
  const extra = docIds.filter((i) => !manifestIds.includes(i));
  const dupes = [...new Set(docIds.filter((i, k) => docIds.indexOf(i) !== k))];
  if (missing.length) problems.push(`hosted but not listed: ${missing.join(', ')}`);
  if (extra.length) problems.push(`listed but not hosted: ${extra.join(', ')}`);
  if (dupes.length) problems.push(`listed twice: ${dupes.join(', ')}`);
  if (!missing.length && !extra.length && !dupes.length && docIds.join() !== manifestIds.join())
    problems.push('listed in a different order from manifests/index.json');

  return { ok: problems.length === 0, games: manifestIds.length, built: rows.length, listed: docIds.length, upToDate: have === want, problems };
}

/**
 * Gate G7. `manifests/declined.json` records the games this loader LOOKED AT and did not host, and why — the
 * judgement belongs on this side, where the attempt was made and the evidence is. The one thing that can rot is
 * the obvious one: a game gets fixed and added, and nobody removes its entry, so the list publishes a reason for
 * a game that is right there. (Five games were unblocked by one emitter fix in a single afternoon.) So: every
 * declined repo must NOT be hosted, every entry must carry a non-empty reason, and no repo may appear twice.
 */
export function checkDeclined() {
  const f = path.join(REPO, DECLINED);
  const problems = [];
  let list = [];
  try { list = JSON.parse(fs.readFileSync(f, 'utf8')); }
  catch (e) { return { ok: false, declined: 0, problems: [`${DECLINED}: ${e.message}`] }; }
  if (!Array.isArray(list)) return { ok: false, declined: 0, problems: [`${DECLINED} is not an array`] };

  const hosted = new Map();  // upstream repo (lower) -> id
  for (const { id } of JSON.parse(fs.readFileSync(path.join(REPO, 'manifests/index.json'), 'utf8'))) {
    const m = JSON.parse(fs.readFileSync(path.join(REPO, `manifests/${id}.json`), 'utf8'));
    const r = m.upstream && m.upstream.repo;
    if (r) hosted.set(r.toLowerCase(), id);
  }
  const seen = new Set();
  for (const e of list) {
    const r = e && typeof e.repo === 'string' ? e.repo : null;
    if (!r) { problems.push(`an entry has no repo: ${JSON.stringify(e).slice(0, 80)}`); continue; }
    if (!e.reason || !String(e.reason).trim()) problems.push(`${r}: no reason`);
    // `short` is what the census table prints; `reason` is the full account, kept for its tooltip and for us
    if (!e.short || !String(e.short).trim()) problems.push(`${r}: no short label`);
    else if (String(e.short).length > 24) problems.push(`${r}: short label is ${String(e.short).length} chars, over 24 — it has to fit a table cell`);
    if (seen.has(r.toLowerCase())) problems.push(`${r}: listed twice`);
    seen.add(r.toLowerCase());
    if (hosted.has(r.toLowerCase())) problems.push(`${r}: declined AND hosted as \`${hosted.get(r.toLowerCase())}\` — remove the entry`);
  }
  return { ok: problems.length === 0, declined: list.length, problems };
}

/**
 * What a game says it IS, read from the files its manifest says the loader loads: `modInfo = { name, author }` and
 * `VERSION = { num }`. Both are the game's own declaration, in its own source — nothing here is a value we chose.
 *
 * ⛔ WHY IT IS READ AND NOT TRUSTED. `manifests/<id>.json` is generated by the census emitter, whose reader looked in
 * `mod.js`; the two oldest games on the roster (`the-modding-tree` 2.0.5.1, `the-burning-tree` 2.0.4) declare
 * `modInfo` in `js/game.js` instead, so their `name` and `version` came out **null** — and the published picker
 * rendered them as `vnull by null` with an empty link for as long as they have been hosted. Same family as the `js/`
 * glob that produced three wrong roster figures: a reader bounded to one file name silently drops whoever put it
 * somewhere else. Measured 2026-09-18 over the roster: this reader reproduces the manifest's `author` on 171/171 and
 * its `name` and `version` on 169/171 — the two it disagrees with being exactly those two nulls.
 */
export function selfDeclared(id) {
  let mod = null, ver = null;
  for (const f of sourcesOf(id, 'loaded').files) {
    const t = fs.readFileSync(f, 'utf8');
    if (!mod) { const i = t.search(/\bmodInfo\s*=\s*\{/); if (i >= 0) mod = t.slice(i, i + 2000); }
    if (!ver) { const j = t.search(/\bVERSION\s*=\s*\{/); if (j >= 0) ver = t.slice(j, j + 600); }
    if (mod && ver) break;
  }
  const str = (block, key) => {
    if (!block) return null;
    const m = new RegExp('\\b' + key + '\\s*:\\s*(["\'`])((?:\\\\.|(?!\\1)[^\\\\])*)\\1').exec(block);
    return m ? m[2] : null;
  };
  return { name: str(mod, 'name'), author: str(mod, 'author'), version: str(ver || mod, 'num') };
}

/**
 * Gate G6b. Every manifest's `name`, `author` and `version` must BE the game's own declaration — so the roster doc,
 * the picker and the census can never drift from what the game says, and no one can hand-write a title for a game
 * that declares one. A game that declares nothing is reported, not accepted silently.
 */
export function checkSelfDeclared({ manifest = readManifest } = {}) {
  const problems = [];
  const index = JSON.parse(fs.readFileSync(path.join(REPO, 'manifests/index.json'), 'utf8'));
  const byId = new Map(index.map((e) => [e.id, e]));
  let checked = 0, undeclared = 0;
  // ⛔ A GAME THAT IS NOT THERE IS A REFUSAL, never "declares nothing" (S0's P3, 2026-09-29): with no games/ at all this
  // check read zero files per game, counted all 175 as undeclared, and exited GREEN — which is exactly what an
  // uninitialised submodule (S2) looks like. So: games/ must exist and hold something, and each game must have at
  // least one of the files its manifest says the loader loads.
  const gamesDir = path.join(REPO, 'games');
  if (!fs.existsSync(gamesDir) || !fs.readdirSync(gamesDir).some((x) => x !== '.git')) return { ok: false, checked: 0, undeclared: 0, problems: ['games/ is absent or empty — nothing to read the games\' own declarations from (an uninitialised submodule?)'] };
  for (const id of GAMES()) {
    const src = sourcesOf(id, 'loaded');
    if (!src.files.length) { problems.push(`${id}: none of the game's loaded files can be read (${src.missing}) — its own declaration is unreadable, which is not the same as "declares nothing"`); continue; }
    const m = manifest(id), own = selfDeclared(id);
    for (const k of ['name', 'author', 'version']) {
      if (own[k] === null) { if (k === 'name') undeclared++; continue; }  // the game declares nothing: not a drift
      if ((m[k] ?? null) !== own[k]) problems.push(`${id}: manifest ${k} ${JSON.stringify(m[k] ?? null)} is not the game\'s own ${JSON.stringify(own[k])} (it declares it in its own source)`);
    }
    const e = byId.get(id);
    if (e && (e.name ?? null) !== (m.name ?? null)) problems.push(`${id}: manifests/index.json says name ${JSON.stringify(e.name ?? null)}, the manifest says ${JSON.stringify(m.name ?? null)}`);
    checked++;
  }
  return { ok: problems.length === 0, checked, undeclared, problems };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  if (process.argv.includes('--check')) {
    const r = checkGamesTable(), d = checkDeclined(), n = checkSelfDeclared();
    for (const p of r.problems) console.error(`${OUT}: ${p}`);
    for (const p of d.problems) console.error(`${DECLINED}: ${p}`);
    for (const p of n.problems) console.error(`manifests: ${p}`);
    if (r.ok && d.ok && n.ok) console.log(`${OUT} up to date — ${r.games} games in manifests/index.json, ${r.listed} listed; ${DECLINED}: ${d.declined} declined, none hosted; ${n.checked} manifest(s) name/author/version = the game's own declaration${n.undeclared ? ` (${n.undeclared} game(s) declare no name of their own)` : ''}`);
    process.exit(r.ok && d.ok && n.ok ? 0 : 1);
  }
  const rows = rosterFromManifests();
  fs.writeFileSync(path.join(REPO, OUT), render(rows));
  console.log(`${OUT}: ${rows.length} games`);
}
